### PR TITLE
window is now visible on all workspaces

### LINKED ISSUE #7: Move electron window across desktops when switching
As of now, the window stays on the same desktop it was created on. It would be good if it moved to the active desktop on swiping left or right to a new desktop

### PR DESCRIPTION
**Pull request by syxanash**
I've used the method `setVisibleOnAllWorkspaces` as documented [here](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetvisibleonallworkspacesvisible)

Resolves #7

### CODE REVIEW

**Comment by will-stone** [comment]
Things to check (a checklist for myself but feel free to go through and document the results if you have time)

- How does it behave in Mission Control? Ideally: scales with other apps and is draggable between workspaces like normal windows.
- What happens when _System Preferences > Mission Control > Displays Have Separate Spaces_ is unchecked in a multi-monitor set-up? Ideally: SS shows on one monitor screen and can be dragged to other monitor.
- What happens when _System Preferences > Mission Control > Displays Have Separate Spaces_ is checked in a multi-monitor set-up? Ideally: SS shows on one monitor screen and can be dragged to other monitor.
- SS is on same screen as another app. Put other app into (green button) fullscreen mode. What happens to SS? Ideally: SS is on top of fullscreen app but this is not important.
- SS must remain on top of all non-fullscreen apps at all times.

**Comment by syxanash** [comment]
> What happens when System Preferences > Mission Control > Displays Have Separate Spaces is checked in a multi-monitor set-up? Ideally: SS shows on one monitor screen and can be dragged to other monitor.

Yes the app remains on top and can be dragged across all monitors. If we have two desktops on the same monitor the app moves from one desktop to the other one selected by the user.

> SS is on same screen as another app. Put other app into (green button) fullscreen mode. What happens to SS? Ideally: SS is on top of fullscreen app but this is not important.

It remains always on top even with full screen applications. (This is exactly what I needed 😆)

> SS must remain on top of all non-fullscreen apps at all times.
yup it does!

**Comment by will-stone** [comment]
Thanks. What about:

> What happens when System Preferences > Mission Control > Displays Have Separate Spaces is unchecked in a multi-monitor set-up? Ideally: SS shows on one monitor screen and can be dragged to other monitor.

Basically, there should be one and only one SS visible at all times.

**Comment by syxanash** [comment]
I can't reproduce that step at the moment :(

**Comment by syxanash** [comment]
just tested that scenario and yes the window appears only on one monitor and it's always visible even when switching to full screen apps.

**Comment by will-stone** [comment]
Sounds good to me. Thanks for testing.

**Comment by syxanash** [comment]
> How does it behave in Mission Control? Ideally: scales with other apps and is draggable between workspaces like normal windows.

I was testing this one and apparently when in Mission Control the window is not draggable across the workspaces but disappears from the current workspace (this I think is the same behaviour that we had before my PR).

**Comment by will-stone** [comment]
Indeed, it is.

This new functionality may need to be an option as users could move workspace and actually not want it to follow them. I can add that in once the React update is done.

**Pull request merged**
